## exercise 1-4.1
* 1x vector
* 2x2
* 3x3
* 4x8


In [46]:
# 1x3 vector
import numpy as np
a = np.array([1,2,3])
print 'dim a:', a.shape

#2x2
b = np.array([[1,2],[4,5]])
print 'dim b:', b.shape

#3x3
c = np.arange(1,10).reshape(3,3)
print c
print 'dim c:', c.shape

#4x8
d = np.arange(1,33).reshape(4,8)
print d
print 'dim d:', d.shape




dim a: (3,)
dim b: (2, 2)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
dim c: (3, 3)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]
dim d: (4, 8)


In [6]:
# import numpy
# create array x
import numpy as np
x = np.array([5,4,3,2,1])
x[2]

3

In [4]:
# print the shape of x
np.shape(x)

(5,)

In [53]:
# create a two dimensional array
y = np.arange(1,13).reshape(4,3)
print y


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
# print shape of 2d array
np.shape(y)

(4, 3)

In [55]:
# reshape the array to 2 x 6
y.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [59]:
# reshape the array to 1 x 12
y = y.reshape(1,12)
y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [60]:
# transpose the array
np.transpose(y)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [68]:
tri = np.arange(1,257).reshape(4,4,4,4)
print tri
print tri.shape
print 4**4

[[[[  1   2   3   4]
   [  5   6   7   8]
   [  9  10  11  12]
   [ 13  14  15  16]]

  [[ 17  18  19  20]
   [ 21  22  23  24]
   [ 25  26  27  28]
   [ 29  30  31  32]]

  [[ 33  34  35  36]
   [ 37  38  39  40]
   [ 41  42  43  44]
   [ 45  46  47  48]]

  [[ 49  50  51  52]
   [ 53  54  55  56]
   [ 57  58  59  60]
   [ 61  62  63  64]]]


 [[[ 65  66  67  68]
   [ 69  70  71  72]
   [ 73  74  75  76]
   [ 77  78  79  80]]

  [[ 81  82  83  84]
   [ 85  86  87  88]
   [ 89  90  91  92]
   [ 93  94  95  96]]

  [[ 97  98  99 100]
   [101 102 103 104]
   [105 106 107 108]
   [109 110 111 112]]

  [[113 114 115 116]
   [117 118 119 120]
   [121 122 123 124]
   [125 126 127 128]]]


 [[[129 130 131 132]
   [133 134 135 136]
   [137 138 139 140]
   [141 142 143 144]]

  [[145 146 147 148]
   [149 150 151 152]
   [153 154 155 156]
   [157 158 159 160]]

  [[161 162 163 164]
   [165 166 167 168]
   [169 170 171 172]
   [173 174 175 176]]

  [[177 178 179 180]
   [181 182 183 184]
   [185 

In [79]:
# indexing method 1
np.add([1,2,3],[3,2,1])


array([4, 4, 4])

In [107]:
# indexing method 2

#Set 1 - Add
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]
print np.add(a,b)

#Set 2 - Subtract

a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]

print np.subtract(a,b)

#Set 3 - Subtract
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]
print np.subtract(a,b)

#Set 4 - Subtract
a = [-101, -201, -33.22, 423, -5.3234, -34]

b = ([601, -501.33, 113, -3.3000003, 'l', 10.999999999999999])

for index, value in enumerate(b):
    if type(value) == str:
        b[index] = -1
print b
print np.subtract(a,b)

[-5 -3 -1  1  3  5]
[ 5  3  1 -1 -3 -5]
[ 702.        -300.33       146.22      -426.3000003    7.3234      -4.234    ]
[601, -501.33, 113, -3.3000003, -1, 10.999999999999998]
[-702.         300.33      -146.22       426.3000003   -4.3234     -45.       ]


## Independent Practice: Topic (20 minutes)
Create 2 arrays. Add them together, subtract them, and do the dot product.
Bonus:

Create a 3 dimensional array
Create a 5 dimensional array

In [136]:
# indexing method 3

a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]
print 'add:' , np.add(a,b)
print 'subtract:',np.subtract(a,b)
print 'dotproduct:',np.dot(a,b)

three = np.arange(1,28).reshape(3,3,3)
print '3d array:', three

five = np.arange((5**5)).reshape(5,5,5,5,5)
#print '5d array:', five
print 'five shape:', five.shape
5**5
six = np.array([[1,2[1,2[1,2[1,2[1,2[1,2]]]]]]])

print 'six shape:' , six.shape

add: [-500.         702.33       -79.78      -419.6999997    3.3234      -8.234    ]
subtract: [ 702.        -300.33       146.22      -426.3000003    7.3234      -4.234    ]
dotproduct: 34918.3910731
3d array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
five shape: (5, 5, 5, 5, 5)


TypeError: 'int' object has no attribute '__getitem__'

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6